### ISSUE TITLE
server create hangs

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/nova-operator#299]
`openstack --debug server create --flavor c1 --image cirros-0.5.2-x86_64-disk --nic net-id=private vm5 --wait`

openstack client got 504:
```
http://nova-public-openstack.apps-crc.testing:80 "POST /v2.1/servers HTTP/1.1" 504 92
RESP: [504] cache-control: no-cache connection: close content-length: 92 content-type: text/html
RESP BODY: Omitted, Content-Type is set to text/html. Only text/plain, application/json responses have their bodies logged.
Unknown Error (HTTP 504)
Traceback (most recent call last):
  File "/home/gibi/.local/lib/python3.11/site-packages/cliff/app.py", line 410, in run_subcommand
    result = cmd.run(parsed_args)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/osc_lib/command/command.py", line 39, in run
    return super(Command, self).run(parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/cliff/display.py", line 117, in run
    column_names, data = self.take_action(parsed_args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/openstackclient/compute/v2/server.py", line 1729, in take_action
    server = compute_client.servers.create(*boot_args, **boot_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/novaclient/v2/servers.py", line 1562, in create
    return self._boot(response_key, *boot_args, **boot_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/novaclient/v2/servers.py", line 887, in _boot
    return self._create('/servers', body, response_key,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/novaclient/base.py", line 363, in _create
    resp, body = self.api.client.post(url, body=body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/keystoneauth1/adapter.py", line 401, in post
    return self.request(url, 'POST', **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gibi/.local/lib/python3.11/site-packages/novaclient/client.py", line 78, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.ClientException: Unknown Error (HTTP 504)
clean_up CreateServer: Unknown Error (HTTP 504)
END return value: 1
```

nova-api-0 pods logs:
```
2023-03-22 17:23:54.283 12 DEBUG nova.api.openstack.wsgi [None req-1c727214-bb04-45fa-94bf-9214b172635d 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] Returning 404 to user: Flavor c1 could not be found. __call__ /usr/lib/python3.9/site-packages/nova/api/openstack/wsgi.py:942
2023-03-22 17:23:54.283 12 INFO nova.api.openstack.requestlog [None req-1c727214-bb04-45fa-94bf-9214b172635d 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] 192.168.130.1 "GET /v2.1/flavors/c1" status: 404 len: 75 microversion: 2.1 time: 0.082676
2023-03-22 17:23:54.287 12 DEBUG nova.api.openstack.wsgi [None req-91a1058c-df04-4435-aa99-c9b176e53e94 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] Calling method '<bound method FlavorsController.index of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f38522bcc70>>' _process_stack /usr/lib/python3.9/site-packages/nova/api/openstack/wsgi.py:513
2023-03-22 17:23:54.290 12 INFO nova.api.openstack.requestlog [None req-91a1058c-df04-4435-aa99-c9b176e53e94 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] 192.168.130.1 "GET /v2.1/flavors" status: 200 len: 333 microversion: 2.1 time: 0.004020
2023-03-22 17:23:54.293 12 DEBUG nova.api.openstack.wsgi [None req-30f1ef57-930c-4aa4-9cde-f9aa5b386912 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] Calling method '<bound method FlavorsController.show of <nova.api.openstack.compute.flavors.FlavorsController object at 0x7f3852246df0>>' _process_stack /usr/lib/python3.9/site-packages/nova/api/openstack/wsgi.py:513
2023-03-22 17:23:54.296 12 INFO nova.api.openstack.requestlog [None req-30f1ef57-930c-4aa4-9cde-f9aa5b386912 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] 192.168.130.1 "GET /v2.1/flavors/7c596f09-3ea0-4f77-8cc1-118e624d9243" status: 200 len: 500 microversion: 2.1 time: 0.003312
2023-03-22 17:23:54.457 12 DEBUG nova.api.openstack.wsgi [None req-147455bd-4973-457c-b8d8-243e846be3dc 1475b41fa12f4ccd917600dbdfab9f4c a715e52df9b14daca69eaa2c93c2add9 - - default default] Action: 'create', calling method: <bound method ServersController.create of <nova.api.openstack.compute.servers.ServersController object at 0x7f385208f8b0>>, body: {"server": {"name": "vm5", "imageRef": "fa062cd8-9cc0-458a-9181-c811e005ae44", "flavorRef": "7c596f09-3ea0-4f77-8cc1-118e624d9243", "min_count": 1, "max_count": 1, "networks": [{"uuid": "6e1cf8b3-6aee-4054-804f-074787a4bd43"}]}} _process_stack /usr/lib/python3.9/site-packages/nova/api/openstack/wsgi.py:511
```
at this point nova-api-0 hangs, then after a while k8s kills the pod and starts a new one.

There is no event in the statefulset nova-api about the restart but by watching the statefulset during the reproduction I see that the availableReplicas goes from 1 to 0 then back to 1.

Content of the log of nova-api-api container:
```
192.168.130.1 - - [22/Mar/2023:17:36:21 +0000] "GET /v2.1/flavors/c1 HTTP/1.1" 404 75 "-" "python-novaclient"
AH01628: authorization result: granted (no directives)
192.168.130.1 - - [22/Mar/2023:17:36:21 +0000] "GET /v2.1/flavors HTTP/1.1" 200 333 "-" "python-novaclient"
AH01628: authorization result: granted (no directives)
192.168.130.1 - - [22/Mar/2023:17:36:21 +0000] "GET /v2.1/flavors/7c596f09-3ea0-4f77-8cc1-118e624d9243 HTTP/1.1" 200 500 "-" "python-novaclient"
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
192.168.130.1 - - [22/Mar/2023:17:36:21 +0000] "POST /v2.1/servers HTTP/1.1" 504 247 "-" "python-novaclient"
AH00470: network write failure in core output filter
AH01628: authorization result: granted (no directives)
AH01628: authorization result: granted (no directives)
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
10.217.0.1 - - [22/Mar/2023:17:36:24 +0000] "GET / HTTP/1.1" 504 247 "-" "kube-probe/1.25"
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
10.217.0.1 - - [22/Mar/2023:17:36:24 +0000] "GET / HTTP/1.1" 504 247 "-" "kube-probe/1.25"
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
10.217.0.1 - - [22/Mar/2023:17:36:24 +0000] "GET / HTTP/1.1" 504 247 "-" "kube-probe/1.25"
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
10.217.0.1 - - [22/Mar/2023:17:36:24 +0000] "GET / HTTP/1.1" 504 247 "-" "kube-probe/1.25"
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
10.217.0.1 - - [22/Mar/2023:17:36:29 +0000] "GET / HTTP/1.1" 504 247 "-" "kube-probe/1.25"
AH00470: network write failure in core output filter
Timeout when reading response headers from daemon process 'nova-api': /usr/bin/nova-api-wsgi
10.217.0.1 - - [22/Mar/2023:17:36:29 +0000] "GET / HTTP/1.1" 504 247 "-" "kube-probe/1.25"
AH00470: network write failure in core output filter
mod_wsgi (pid=12): Shutdown requested 'nova-api'.
```

Based on this the nova-api-wsgi just hang and that blocked the kube-probe requests as well.

**Comment by gibizer** [comment]
this can be reproduced in ~1 in 5 boot request.

**Comment by SeanMooney** [comment]
this could also be related to the fact the API can only process one request at a time currently
because of apache

**Comment by gibizer** [comment]
Not seen this recently

**Comment by gibizer** [comment]
Not seen this recently
